import { SignalGroup } from "./core";

export const SIGNALS = {
  appQuit: SignalGroup.fromStr("app:quit"),
  themeToggle: SignalGroup.fromStr("theme:toggle"),
  focusToggleCodeChips: SignalGroup.fromStr("focus:toggle_code_chips"),
  chipsMove: SignalGroup.fromStr("chips:move"),
  chipsToggleSelected: SignalGroup.fromStr("chips:toggle_selected"),
  cursorMove: SignalGroup.fromStr("cursor:move"),
  cursorPage: SignalGroup.fromStr("cursor:page"),
  cursorChanged: SignalGroup.fromStr("cursor:changed"),
  visualToggle: SignalGroup.fromStr("visual:toggle"),
  visualExit: SignalGroup.fromStr("visual:exit"),
  selectionYank: SignalGroup.fromStr("selection:yank"),
  filesToggleExplorer: SignalGroup.fromStr("files:toggle_explorer"),
  filesEnterOrOpen: SignalGroup.fromStr("files:enter_or_open"),
  filesEnterDirectory: SignalGroup.fromStr("files:enter_directory"),
  filesParentDir: SignalGroup.fromStr("files:parent_dir"),
  filesCollapseCurrent: SignalGroup.fromStr("files:collapse_current"),
  navJumpTop: SignalGroup.fromStr("nav:jump_top"),
  navJumpBottom: SignalGroup.fromStr("nav:jump_bottom"),
  navJumpNextFile: SignalGroup.fromStr("nav:jump_next_file"),
  navJumpPrevFile: SignalGroup.fromStr("nav:jump_prev_file"),
  navJumpNextAgent: SignalGroup.fromStr("nav:jump_next_agent"),
  agentDeleteAtCursor: SignalGroup.fromStr("agent:delete_at_cursor"),
  promptClose: SignalGroup.fromStr("prompt:close"),
  promptSubmit: SignalGroup.fromStr("prompt:submit"),
  promptFieldCycle: SignalGroup.fromStr("prompt:field_cycle"),
  promptModelCycle: SignalGroup.fromStr("prompt:model_cycle"),
  promptThinkingCycle: SignalGroup.fromStr("prompt:thinking_cycle"),
  promptModelsRefresh: SignalGroup.fromStr("prompt:models_refresh"),
  promptInputKey: SignalGroup.fromStr("prompt:input_key"),
  promptSubmission: SignalGroup.fromStr("prompt:submission"),
  promptFocusModeChange: SignalGroup.fromStr("prompt:focus_mode_change"),
  agentRenderRequested: SignalGroup.fromStr("agent:render_requested"),
  scrollVertical: SignalGroup.fromStr("scroll:vertical"),
  systemStdoutResize: SignalGroup.fromStr("system:stdout_resize"),
  workspaceChanged: SignalGroup.fromStr("workspace:changed"),
} as const;
