import { SyntaxStyle } from "@opentui/core";

export const syntaxStyle = SyntaxStyle.fromTheme([
  { scope: ["default"], style: { foreground: "#d1d5db" } },
  { scope: ["text"], style: { foreground: "#d1d5db" } },
  { scope: ["comment"], style: { foreground: "#6b7280", italic: true } },
  { scope: ["punctuation.comment"], style: { foreground: "#6b7280" } },
  { scope: ["keyword.control"], style: { foreground: "#93c5fd", bold: true } },
  { scope: ["keyword.operator"], style: { foreground: "#f8fafc" } },
  { scope: ["keyword"], style: { foreground: "#60a5fa", bold: true } },
  { scope: ["boolean"], style: { foreground: "#f59e0b", bold: true } },
  { scope: ["null"], style: { foreground: "#f59e0b", bold: true } },
  { scope: ["builtin"], style: { foreground: "#f472b6" } },
  { scope: ["variable"], style: { foreground: "#e5e7eb" } },
  { scope: ["variable.builtin"], style: { foreground: "#fda4af" } },
  { scope: ["parameter"], style: { foreground: "#bfdbfe" } },
  { scope: ["string"], style: { foreground: "#34d399" } },
  { scope: ["string.escape"], style: { foreground: "#5eead4" } },
  { scope: ["regexp"], style: { foreground: "#86efac" } },
  { scope: ["number"], style: { foreground: "#f59e0b" } },
  { scope: ["float"], style: { foreground: "#f59e0b" } },
  { scope: ["integer"], style: { foreground: "#f59e0b" } },
  { scope: ["function.call"], style: { foreground: "#67e8f9" } },
  { scope: ["function"], style: { foreground: "#22d3ee" } },
  { scope: ["method"], style: { foreground: "#22d3ee" } },
  { scope: ["constructor"], style: { foreground: "#38bdf8" } },
  { scope: ["type"], style: { foreground: "#a78bfa" } },
  { scope: ["class"], style: { foreground: "#c4b5fd" } },
  { scope: ["interface"], style: { foreground: "#c4b5fd" } },
  { scope: ["namespace"], style: { foreground: "#c4b5fd" } },
  { scope: ["constant"], style: { foreground: "#f472b6" } },
  { scope: ["enum"], style: { foreground: "#f472b6" } },
  { scope: ["property"], style: { foreground: "#38bdf8" } },
  { scope: ["field"], style: { foreground: "#38bdf8" } },
  { scope: ["attribute"], style: { foreground: "#f9a8d4" } },
  { scope: ["tag"], style: { foreground: "#fb7185" } },
  { scope: ["operator"], style: { foreground: "#f8fafc" } },
  { scope: ["punctuation"], style: { foreground: "#9ca3af" } },
  { scope: ["delimiter"], style: { foreground: "#9ca3af" } },
  { scope: ["punctuation.special"], style: { foreground: "#94a3b8", bold: true } },
  { scope: ["markup.heading"], style: { foreground: "#f8fafc", bold: true } },
  { scope: ["markup.heading.1"], style: { foreground: "#f97316", bold: true } },
  { scope: ["markup.heading.2"], style: { foreground: "#f59e0b", bold: true } },
  { scope: ["markup.heading.3"], style: { foreground: "#22c55e", bold: true } },
  { scope: ["markup.heading.4"], style: { foreground: "#06b6d4", bold: true } },
  { scope: ["markup.heading.5"], style: { foreground: "#3b82f6", bold: true } },
  { scope: ["markup.heading.6"], style: { foreground: "#a855f7", bold: true } },
  { scope: ["markup.strong"], style: { foreground: "#ffffff", bold: true } },
  { scope: ["markup.italic"], style: { foreground: "#e2e8f0", italic: true } },
  { scope: ["markup.strikethrough"], style: { foreground: "#94a3b8", dim: true } },
  { scope: ["markup.raw"], style: { foreground: "#fca5a5" } },
  { scope: ["markup.list"], style: { foreground: "#93c5fd", bold: true } },
  { scope: ["markup.link"], style: { foreground: "#60a5fa" } },
  { scope: ["markup.link.label"], style: { foreground: "#bfdbfe", underline: true } },
  { scope: ["markup.link.url"], style: { foreground: "#38bdf8", underline: true } },
]);
